### PR TITLE
added my name for finding and uploading pre-1.2 (Cert-CL-3532353)

### PR DESCRIPTION
**Pull request by 0ez**
i gotta be everywhere

### CODE REVIEW

**Comment by Fischsalat** [comment]
Yea, ofc, you did a great job by going to ThePirateBay.org and searching for "Fortnite". Pretty sure there weren't at least 10 other people who did the same before.

Next time you try to add credits to yourself, maybe add them for something you actually did.

**Comment by Fischsalat** [comment]
proof

**Comment by Fischsalat** [comment]
image

**Comment by 0ez** [comment]
look at gdrive info lmfao

**Comment by 0ez** [comment]
me and crush found it but ive uploaded it lol

**Comment by 0ez** [comment]
image
omg can u see "artii" i think u remember my old nickname

**Pull request closed without merging**
